language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
    fast_finish: true

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - vendor/bin/phpunit
    - vendor/bin/phpstan analyse -l 8 src tests
